import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,MapPin,CalendarDays,Users,ChevronRight,Heart,Star,ShieldCheck,Headphones,IndianRupee,Menu,X,ArrowRight} from 'lucide-react';
import './style.css';

const destinations=[
['Goa','Beach escape','https://images.unsplash.com/photo-1512343879784-a960bf40e7f2'],
['Kashmir','Mountain retreat','https://images.unsplash.com/photo-1595815771614-ade9d652a65d'],
['Kerala','Tropical paradise','https://images.unsplash.com/photo-1602216056096-3b40cc0c9944'],
['Rajasthan','Royal getaway','https://images.unsplash.com/photo-1477587458883-47145ed94245'],
['Bali','Island escape','https://images.unsplash.com/photo-1537996194471-e657df975ab4'],
['Dubai','Luxury break','https://images.unsplash.com/photo-1512453979798-5ea266f8880c']
];
const packages=[
['Goa Weekend Escape','Goa','3 Days / 2 Nights','₹12,999','₹16,999','https://images.unsplash.com/photo-1512343879784-a960bf40e7f2','4.8'],
['Kashmir Paradise','Kashmir','6 Days / 5 Nights','₹24,999','₹31,999','https://images.unsplash.com/photo-1595815771614-ade9d652a65d','4.9'],
['Kerala Backwaters','Kerala','5 Days / 4 Nights','₹19,999','₹25,999','https://images.unsplash.com/photo-1602216056096-3b40cc0c9944','4.8'],
['Royal Rajasthan','Rajasthan','7 Days / 6 Nights','₹28,999','₹36,999','https://images.unsplash.com/photo-1477587458883-47145ed94245','4.7'],
['Bali Island Holiday','Bali','5 Days / 4 Nights','₹42,999','₹49,999','https://images.unsplash.com/photo-1537996194471-e657df975ab4','4.9'],
['Dubai Premium Break','Dubai','4 Days / 3 Nights','₹35,999','₹42,999','https://images.unsplash.com/photo-1512453979798-5ea266f8880c','4.8']
];

function App(){
 const [q,setQ]=useState(''); const [modal,setModal]=useState(null); const [done,setDone]=useState(false); const [menu,setMenu]=useState(false);
 const shown=destinations.filter(d=>d[0].toLowerCase().includes(q.toLowerCase()));
 async function submit(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.package_id=modal?.[0];try{await fetch((import.meta.env.VITE_API_URL||'http://localhost:5000/api')+'/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}catch{}setDone(true)}
 return <><header><div className="brand">wanderly<span>.</span></div><nav className={menu?'open':''}><a href="#destinations">Destinations</a><a href="#packages">Packages</a><a href="#why">Why Wanderly</a><a href="#reviews">Reviews</a><button onClick={()=>document.getElementById('packages').scrollIntoView()}>Explore trips <ArrowRight size={15}/></button></nav><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <section className="hero"><div className="heroCopy"><div className="pill">✦ INDIA'S FAVOURITE TRAVEL PARTNER</div><h1>Make memories<br/><em>worth travelling for.</em></h1><p>Discover handpicked holidays, beautiful stays and unforgettable experiences — all planned around you.</p><div className="searchBox"><div><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Where do you want to go?"/></div><button onClick={()=>document.getElementById('destinations').scrollIntoView()}>Search</button></div><div className="trust"><div><b>10,000+</b><span>Happy travellers</span></div><div><b>4.9/5</b><span>Average rating</span></div><div><b>24/7</b><span>Travel support</span></div></div></div><div className="heroVisual"><img src="https://images.unsplash.com/photo-1527631746610-bca00a040d60"/><div className="heroCard"><span>Next adventure</span><b>Where will you go?</b><small>🌴 Goa · ₹12,999 onwards</small></div></div></section>
 <section id="destinations"><div className="heading"><div><span className="kicker">EXPLORE INDIA & BEYOND</span><h2>Places you'll love</h2></div><a href="#destinations">View all <ChevronRight size={17}/></a></div><div className="destinationGrid">{shown.map(d=><div className="dest" key={d[0]}><img src={d[2]}/><button className="heart"><Heart size={17}/></button><div><span>{d[1]}</span><h3>{d[0]}</h3></div></div>)}</div></section>
 <section className="offer"><div><span className="kicker">LIMITED-TIME OFFER</span><h2>Plan your escape.<br/><em>Save up to 25%.</em></h2><p>Summer getaways, romantic escapes and family holidays at prices you'll love.</p><button onClick={()=>document.getElementById('packages').scrollIntoView()}>View offers <ArrowRight size={16}/></button></div><div className="offerPic"><img src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e"/><span>UP TO 25% OFF</span></div></section>
 <section id="packages" className="packageSection"><div className="heading"><div><span className="kicker">CURATED GETAWAYS</span><h2>Popular packages</h2></div><a href="#packages">View all <ChevronRight size={17}/></a></div><div className="packageGrid">{packages.map(p=><article className="package" key={p[0]}><div className="packageImg"><img src={p[5]}/><span className="tag">BEST SELLER</span><button className="heart"><Heart size={17}/></button></div><div className="packageInfo"><div className="rating"><Star size={14} fill="currentColor"/> {p[6]}</div><h3>{p[0]}</h3><p><MapPin size={14}/> {p[1]} <span>·</span> <CalendarDays size={14}/> {p[2]}</p><div className="price"><div><small>Starting from</small><b>{p[3]}</b> <del>{p[4]}</del></div><button onClick={()=>{setModal(p);setDone(false)}}>Book now</button></div></div></article>)}</div></section>
 <section id="why" className="why"><div className="whyIntro"><span className="kicker">THE WANDERLY PROMISE</span><h2>Travel should feel<br/><em>effortless.</em></h2><p>From the first search to the moment you return home, we're here to make every part of your journey simpler.</p></div><div className="whyGrid"><div><ShieldCheck/><h3>Trusted & secure</h3><p>Verified stays, transparent pricing and secure booking.</p></div><div><Headphones/><h3>Always here</h3><p>Real travel experts available whenever you need us.</p></div><div><IndianRupee/><h3>Best value</h3><p>Great experiences at honest Indian prices.</p></div><div><Star/><h3>Loved by travellers</h3><p>Thousands of journeys and 4.9/5 average reviews.</p></div></div></section>
 <section id="reviews" className="reviews"><span className="kicker">TRAVELLER STORIES</span><h2>Don't just take our word for it.</h2><div className="reviewGrid">{[['“The Kashmir trip was absolutely magical. Everything was beautifully planned.”','Ananya · Hyderabad'],['“From booking to checkout, Wanderly made our Goa trip completely stress-free.”','Rahul · Bengaluru'],['“The best part? No hidden charges. Exactly what was promised.”','Priya · Mumbai']].map(r=><div className="review"><div className="stars">★★★★★</div><p>{r[0]}</p><b>{r[1]}</b></div>)}</div></section>
 <footer><div className="brand">wanderly<span>.</span></div><div><b>Explore</b><p>Destinations · Packages · Hotels</p></div><div><b>Company</b><p>About · Contact · Careers</p></div><div><b>Support</b><p>Help Centre · 24/7 Travel Support</p></div><small>© 2026 Wanderly India</small></footer>
 {modal&&<div className="overlay"><div className="modal">{done?<div className="success"><div className="check">✓</div><h2>You're all set!</h2><p>Your booking request for <b>{modal[0]}</b> has been received.</p><button onClick={()=>setModal(null)}>Done</button></div>:<><button className="close" onClick={()=>setModal(null)}>×</button><span className="kicker">BOOK YOUR GETAWAY</span><h2>{modal[0]}</h2><p className="modalPrice">{modal[3]} <span>per person</span></p><form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="email" required type="email" placeholder="Email address"/><div className="two"><input name="travel_date" required type="date"/><input name="guests" required min="1" type="number" defaultValue="2"/></div><button type="submit">Confirm booking <ArrowRight size={16}/></button></form></>}</div></div>}</>
}
createRoot(document.getElementById('root')).render(<App/>);
